### ISSUE TITLE
what's the typeface?

### ISSUE THREAD

**Issue by ianstormtaylor** [voodootikigod/logo.js#38]
would be awesome to add an editable `.ai` and `.psd` file

**Comment by waldyrious** [comment]
@voodootikigod I suppose it would be worth considering an openly-licensed font that matches the geometry of these two letters as closely as possible. Otherwise it could be problematic to have these outlines licensed under MIT, especially since fair-use doctrine is only supported in US and [a few other countries](https://en.wikipedia.org/wiki/Fair_use#Influence_internationally).

**Comment by igorasantos** [comment]
> for better/worse: neutraface 2 text bold 340pt http://www.houseind.com/fonts/neutraface2 gives you the exact match. Many have found open sans to provide similar enough to use. Happy to provide outlines of letters if you want to create one (like jshint uses).

@voodootikigod, so the fontface used on the JS community logo has a commercial licence?
Why the whole logo would have an open/MIT licence, if the fontface (an essencial part of the logo) don't have it?
